name: Build/Release

on:
    push:
        tags:
            - '*'

jobs:
    release-pkg:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                include:
                    - os: ubuntu-latest
                      platform: linux

        steps:
            - id: get_version
              uses: battila7/get-version-action@v2
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16
                  cache: 'npm'
            - run: sudo apt-get install -y zip
            - name: install dependencies
              run: npm install
            - name: build-pkg ${{ matrix.platform }}
              run: npm run pkg:build
            - name: pack-pkg ${{ matrix.platform }}
              run: tar -zcf TON-Stratum-Miner-${{ steps.get_version.outputs.version-without-v }}-linux-headless.tar.gz TON-Stratum-Miner
            - run: mkdir TON_Stratum_Miner_HiveOS
            - run: mkdir TON_Stratum_Miner_HiveOS/bin
            - run: cp ./bin/opencl-18 ./bin/cuda-18 ./TON_Stratum_Miner_HiveOS/bin
            - run: cp -r ./config/ ./TON_Stratum_Miner_HiveOS
            - run: cp -r ./data/ ./TON_Stratum_Miner_HiveOS
            - run: cp ./hiveos/* ./TON_Stratum_Miner_HiveOS
            - run: cp ./TON-Stratum-Miner/TON-Stratum-Miner ./TON_Stratum_Miner_HiveOS
            - run: chmod 777 ./TON_Stratum_Miner_HiveOS/h-config.sh
            - run: chmod 777 ./TON_Stratum_Miner_HiveOS/h-run.sh
            - run: chmod 777 ./TON_Stratum_Miner_HiveOS/h-stats.sh
            - run: chmod 777 ./TON_Stratum_Miner_HiveOS/TON-Stratum-Miner
            - run: tar -zcf TON_Stratum_Miner_HiveOS-${{ steps.get_version.outputs.version-without-v }}.tar.gz TON_Stratum_Miner_HiveOS
            - run: mkdir TON_Stratum_Miner_msOS
            - run: mkdir TON_Stratum_Miner_msOS/bin
            - run: cp ./bin/opencl-18 ./bin/cuda-18 ./TON_Stratum_Miner_msOS/bin
            - run: cp -r ./config/ ./TON_Stratum_Miner_msOS
            - run: cp -r ./data/ ./TON_Stratum_Miner_msOS
            - run: cp ./integrations/minerstat/* ./TON_Stratum_Miner_msOS
            - run: cp ./TON-Stratum-Miner/TON-Stratum-Miner ./TON_Stratum_Miner_msOS
            - run: chmod 777 ./TON_Stratum_Miner_msOS/api
            - run: chmod 777 ./TON_Stratum_Miner_msOS/TON-Stratum-Miner
            - run: tar -zcf TON_Stratum_Miner_msOS-${{ steps.get_version.outputs.version-without-v }}.tar.gz -C TON_Stratum_Miner_msOS .
            - run: mkdir TON_Stratum_Miner_raveOS
            - run: mkdir TON_Stratum_Miner_raveOS/bin
            - run: cp ./bin/opencl-18 ./bin/cuda-18 ./TON_Stratum_Miner_raveOS/bin
            - run: cp -r ./data/ ./TON_Stratum_Miner_raveOS
            - run: cp -r ./integrations/raveos/* ./TON_Stratum_Miner_raveOS
            - run: cp ./TON-Stratum-Miner/TON-Stratum-Miner ./TON_Stratum_Miner_raveOS
            - run: chmod 777 ./TON_Stratum_Miner_raveOS/TON-Stratum-Miner
            - run: cd TON_Stratum_Miner_raveOS && zip -r ../TON_Stratum_Miner_raveOS-${{ steps.get_version.outputs.version-without-v }}.zip ./* && cd -
            - uses: meeDamian/github-release@2.0
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  name: ${{ steps.get_version.outputs.version-without-v }}
                  draft: true
                  gzip: false
                  files: >
                      TON-Stratum-Miner-${{ steps.get_version.outputs.version-without-v }}-linux-headless.tar.gz
                      TON_Stratum_Miner_HiveOS-${{ steps.get_version.outputs.version-without-v }}.tar.gz
                      TON_Stratum_Miner_msOS-${{ steps.get_version.outputs.version-without-v }}.tar.gz
                      TON_Stratum_Miner_raveOS-${{ steps.get_version.outputs.version-without-v }}.zip

    release:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                include:
                    - os: windows-latest
                      platform: windows
                    - os: ubuntu-latest
                      platform: linux

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16
                  cache: 'npm'
            - name: install dependencies
              run: npm install
            - name: release ${{ matrix.platform }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: npm run app:release -- --${{ matrix.platform }}
